using HotelBookingManager.dao.client;
using HotelBookingManager.domain.dto;
using HotelBookingManager.GUI;
using HotelBookingManager.service.client;
using HotelBookingManager.util.db;
using System;
using System.Collections.Generic;
using System.Windows;

namespace HotelBookingManager
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private DBConnection connection;
        private List<Client> clients;
        private IClientService clientService;

        public MainWindow()
        {
            connection = DBConnection.Instance();
            clientService = new ClientServiceImpl(new ClientDaoImpl(connection));

            InitializeComponent();
            InitializeForm();
        }

        private void InitializeForm()
        {
            clients = clientService.GetAllClients();
            clientDataGrid.ItemsSource = clients;
        }

        private void clientDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            clientDataGrid.Columns[0].Visibility = Visibility.Hidden;
            clientDataGrid.Columns[1].Header = "ФИО";
            clientDataGrid.Columns[2].Header = "Адрес";
            clientDataGrid.Columns[3].Header = "E-mail";
            clientDataGrid.Columns[4].Header = "Телефон";
        }

        private void addClientButton_Click(object sender, RoutedEventArgs e)
        {
            Client client = new Client();

            ClientCreateWindow clientProfileWindow = new ClientCreateWindow(true, client, clientService);
            var result = clientProfileWindow.ShowDialog();

            if (result == true)
            {
                clientService.AddClient(client);
                clientDataGrid.ItemsSource = clientService.GetAllClients();
            }
        }

        private void editClientButton_Click(object sender, RoutedEventArgs e)
        {
            if (clientDataGrid.SelectedItem != null)
            {
                Client client = (Client)clientDataGrid.SelectedItem;
                ClientCreateWindow clientProfileWindow = new ClientCreateWindow(false, client, clientService);
                var result = clientProfileWindow.ShowDialog();

                if (result == true)
                {
                    clientService.UpdateClient(client);
                    clientDataGrid.ItemsSource = clientService.GetAllClients();
                }
            }
        }

        private void deleteClientButton_Click(object sender, RoutedEventArgs e)
        {
            if (clientDataGrid.SelectedItem != null)
            {
                Client client = (Client)clientDataGrid.SelectedItem;
                MessageBoxResult messageBoxResult = MessageBox.Show("Вы действительно хотите удалить запись?", "Подтверждение удаления", MessageBoxButton.YesNo, MessageBoxImage.Warning);
                if (messageBoxResult == MessageBoxResult.Yes)
                {
                    clientService.DeleteClientById(client.Id);
                    clientDataGrid.ItemsSource = clientService.GetAllClients();
                }
            }
        }

        private void refreshClientButton_Click(object sender, RoutedEventArgs e)
        {
            List<Client> clients = clientService.GetAllClients();
            clientDataGrid.ItemsSource = clients;
        }
    }
}
